---
# This section commented out until packages have real repos
# Until then, curl bash install is really the only way

# OS-specific install routines
#- include: install-RedHat.yml
#  when: ansible_os_family == 'RedHat'

#- include: install-Debian.yml
#  when: ansible_os_family == 'Debian'

- include: curlinstall.yml

- include: config.yml

- name: ensure rexray is running
  service:
    name: rexray
    state: started
  when: rexray_service

- name: CoreOS | Add opt-path.sh to profile.d for adding rexray PATH
  raw: >
          printf "%s\n%s"
          "#! /usr/bin/bash"
          "PATH=\$PATH:{{ rexray_bin_dir }}"
          > /etc/profile.d/opt-path.sh

- name: CoreOS | Change permissions and ownership for opt-path.sh to run as root
  raw: chmod 0755 /etc/profile.d/opt-path.sh && chown root /etc/profile.d/opt-path.sh

- name: Check for flexrex install     
  stat: 
    path: /var/lib/rexray/scripts/flexrex
  register: flexrex

- name: install flexrex
  shell: /opt/bin/rexray flexrex install --path /etc/kubernetes/volumeplugins/flexrex
  when: rexray_flexrex_enabled && not flexrex.stat.exists
  notify:
    - restart rexray
